### ISSUE TITLE
chore: remove hard coded strings and hard coded text

### ISSUE THREAD

**Issue by abhijitramesh** [immadisairaj/CodeforcesApp#12]
**Describe the bug**
There are lots of hard-coded strings and text in the app remove these and extract the corresponding string resources

**Comment by adarshsiva** [comment]
Can i work on this?

**Comment by aman-g0yaa** [comment]
Can i solve this issue ?

**Comment by immadisairaj** [comment]
> Can i solve this issue ?

@amangoyal2339 Don't try to ask for an issue which is already asked or claimed by someone. You can do it only when the issue is free.
