### ISSUE TITLE
chore: Use dimensions from dimen resources.

### ISSUE THREAD

**Issue by abhijitramesh** [immadisairaj/CodeforcesApp#14]
**Describe the feature you'd like**
Currently, the xml files are using hardcoded dimensions. Store those dimensions in the dimens resource files and use them from there.

**Comment by aman-g0yaa** [comment]
can I solve this issue ?

**Comment by aman-g0yaa** [comment]
when I opened the project in android studio error was shown that new version of build gradle was available. how should i fix it?
 should I make a issue to fix the errors?

**Comment by aman-g0yaa** [comment]
I have fixed this issue , unfortunately some file named idea was added which I think is unnecessary. I will fix it and send pr tomorrow.

**Comment by immadisairaj** [comment]
> when I opened the project in android studio error was shown that new version of build gradle was available. how should i fix it?
> should I make a issue to fix the errors?

@amangoyal2339 this conversation is only related to particular issue. These kind of discussions should be done in gutter channel.
