### ISSUE TITLE
Usable as landscape also

### ISSUE THREAD

**Issue by immadisairaj** [immadisairaj/CodeforcesApp#7]
**Describe the feature you'd like**

Now the application runs only for potrait (declared as potrait in manifests). To make it also work in landscape mode.

**Would you like to work on the issue?**

No

**Comment by adarshsiva** [comment]
Can I work on this issue?

**Comment by aman-g0yaa** [comment]
Shall I solve this issue?

**Comment by aman-g0yaa** [comment]
Sorry I did not  realize it was a pr . I wont make this mistake again
