### ISSUE TITLE
Use snackbar instead of Toast

### ISSUE THREAD

**Issue by immadisairaj** [immadisairaj/CodeforcesApp#8]
**Describe the feature you'd like**

Replace the Toast with snackbar.

**Would you like to work on the issue?**

No

**Comment by aman-g0yaa** [comment]
I would like to work on this .

**Comment by Kshitij09** [comment]
I'm working on this issue. Will submit a PR soon

**Comment by Kshitij09** [comment]
`super.onBackPressed()` is immediately called after `snackbar.show()` and snackbar needs `parentlayout `which wasn't required in case of Toast. Hence the `Snackbar` is not shown if we keep immediate call to `onBackPressed()`. Turnaround would be `postDelayed()` call to same. Is that fine with you ?
